/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "on-primary-container": "#7c839b",
        "on-tertiary-fixed": "#002113",
        "on-secondary-fixed-variant": "#004395",
        "on-primary-fixed-variant": "#3f465c",
        "primary-fixed": "#dae2fd",
        "inverse-on-surface": "#eaf1ff",
        "surface-bright": "#f8f9ff",
        "surface": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "error": "#ba1a1a",
        "on-tertiary-container": "#009668",
        "primary-container": "#131b2e",
        "background": "#f8f9ff",
        "secondary": "#0058be",
        "surface-dim": "#cbdbf5",
        "tertiary": "#000000",
        "tertiary-fixed-dim": "#4edea3",
        "surface-tint": "#565e74",
        "tertiary-fixed": "#6ffbbe",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "secondary-container": "#2170e4",
        "primary-fixed-dim": "#bec6e0",
        "on-primary": "#ffffff",
        "outline": "#76777d",
        "on-secondary-fixed": "#001a42",
        "secondary-fixed-dim": "#adc6ff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#005236",
        "on-secondary-container": "#fefcff",
        "on-surface-variant": "#45464d",
        "tertiary-container": "#002113",
        "surface-container-high": "#dce9ff",
        "surface-container-low": "#eff4ff",
        "primary": "#000000",
        "secondary-fixed": "#d8e2ff",
        "on-primary-fixed": "#131b2e",
        "on-background": "#0b1c30",
        "surface-container": "#e5eeff",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c6c6cd",
        "on-secondary": "#ffffff",
        "inverse-primary": "#bec6e0",
        "on-surface": "#0b1c30",
        "inverse-surface": "#213145"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "3xl": "64px",
        "xs": "4px",
        "sm": "8px",
        "base": "4px",
        "2xl": "48px",
        "lg": "24px",
        "gutter": "24px",
        "xl": "32px",
        "container-max": "1440px",
        "md": "16px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
